version: "3.8"

services:
  app:
    container_name: fastapi_task_app
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: fastapi_task_app_db
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: fastapi-task-app-db
    hostname: postgres
    restart: always

volumes:
  postgres_data:
